datos = read.csv("input.csv")
file_nameCOV = read.csv("cov.csv")
ExpDes <- c("Lattice")
BiplotFormat <- c("pdf")
traits <- c("YLD")
typecov <- c("env")
tmp <- c("30300")
selected <- c("Batan,Toluca,Obregon,AguaFria,Tlatizapan,Celaya,Tuxtla,Ameca")
source("/home/dquoc/galaxy/tools/PLS/PLS.R")
PLSR()
